package it.com.atlassian.webdriver.pageobjects.components;

import com.atlassian.webdriver.pageobjects.components.AbstractWebDriverMenu;
import com.atlassian.webdriver.utils.Check;
import com.atlassian.webdriver.utils.by.ByJquery;
import it.com.atlassian.webdriver.pageobjects.page.RefAppAUIPage;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

/**
 * Represents the JQuery menu that is present on the JQueryPage. This page is generated by the JQueryServlet plugin
 * that is installed into RefApp
 */
public class AdminDropDownMenu extends AbstractWebDriverMenu<AdminDropDownMenu>
{
    @FindBy(id="aui_link")
    private WebElement auiLink;

     public AdminDropDownMenu()
    {
        super(By.id("menu"));
        //super(ByJquery.$("#menu_link").parent("dl"));
    }

    @Override
    protected void activate(WebElement rootElement)
    {
        rootElement.findElement(By.tagName("a")).click();
    }

    @Override
    protected boolean isOpen(WebElement rootElement)
    {
        return Check.elementIsVisible(By.tagName("ul"), rootElement);
    }

    public RefAppAUIPage gotoAuiPageLink()
    {
        auiLink.click();
        return pageBinder.bind(RefAppAUIPage.class);
    }
}
