package it.com.atlassian.webdriver.pageobjects.components;

import com.atlassian.pageobjects.PageBinder;
import com.atlassian.pageobjects.binder.Init;
import com.atlassian.webdriver.AtlassianWebDriver;
import com.atlassian.webdriver.pageobjects.component.ActivatedComponent;
import com.atlassian.webdriver.pageobjects.element.ElementBy;
import com.atlassian.webdriver.pageobjects.element.Element;
import it.com.atlassian.webdriver.pageobjects.page.RefAppAUIPage;
import org.openqa.selenium.By;

import javax.inject.Inject;

/**
 * Represents the JQuery menu that is present on the JQueryPage. This page is generated by the JQueryServlet plugin
 * that is installed into RefApp
 */
public class AdminMenu implements ActivatedComponent<AdminMenu>
{
    @Inject
    protected AtlassianWebDriver driver;

    @Inject
    protected PageBinder pageBinder;

    @ElementBy(id="aui_link")
    private Element auiLink;

    @ElementBy(id="menu")
    private Element rootElement;

    private Element triggerElement;
    private Element viewElement;

    @Init
    public void intialize()
    {
        triggerElement = rootElement.find(By.tagName("a"));
        viewElement = rootElement.find(By.tagName("ul"));
    }

    public RefAppAUIPage gotoAuiPageLink()
    {
        auiLink.click();
        return pageBinder.bind(RefAppAUIPage.class);
    }

    public Element trigger()
    {
        return triggerElement;
    }

    public Element view()
    {
        return viewElement;
    }

    public AdminMenu open()
    {
        if(!isOpen())
        {
            trigger().click();
            view().timed().isVisible().waitFor(true);
        }
        return this;
    }

    public AdminMenu close()
    {
        if(isOpen())
        {
            trigger().click();
            view().timed().isVisible().waitFor(false);
        }

        return this;
    }

    public boolean isOpen()
    {
        return view().isVisible();
    }
}
