package it.com.atlassian.webdriver.pageobjects.components;

import com.atlassian.pageobjects.PageBinder;
import com.atlassian.pageobjects.binder.Init;
import com.atlassian.webdriver.AtlassianWebDriver;
import com.atlassian.webdriver.pageobjects.component.ActivatedComponent;
import com.atlassian.webdriver.pageobjects.element.Element;
import it.com.atlassian.webdriver.pageobjects.components.aui.AuiDropDownMenu;
import it.com.atlassian.webdriver.pageobjects.page.RefAppJQueryPage;
import org.openqa.selenium.By;

import javax.inject.Inject;
import java.util.List;

/**
 * Represents the Links menu that is present in the AUIPage. This page is generated by the AUIServlet plugin that is
 * installed in the RefApp
 */
public class LinksMenu implements ActivatedComponent<LinksMenu>
{
    @Inject
    private AtlassianWebDriver driver;

    @Inject
    private PageBinder pageBinder;

    private AuiDropDownMenu auiMenu;

    @Init
    public void initialize()
    {
        auiMenu = pageBinder.bind(AuiDropDownMenu.class, By.id("dropDown-standard"));
    }

    public Element trigger()
    {
        return auiMenu.trigger();
    }

    public Element view()
    {
        return auiMenu.view();
    }

    public LinksMenu open()
    {
        auiMenu.open();
        return this;
    }

    public LinksMenu close()
    {
        auiMenu.close();
        return this;
    }

    public boolean isOpen()
    {
        return auiMenu.isOpen();
    }

    public List<String> getItems()
    {
        return auiMenu.getItems();
    }

    public RefAppJQueryPage gotoJQueryPage()
    {
        view().find(By.linkText("JQuery Page")).click();
        return pageBinder.bind(RefAppJQueryPage.class);
    }
}
